name: Push to Docker Hub

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
      -
        name: Generate meta data
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/rubocop
          tags: |
            type=ref,event=tag,priority=900
            type=match,pattern=ruby\d+\.\d+,priority=850
            type=match,pattern=\d+\.\d+.\d+,priority=800
      -
        name: Login
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Pull and Test
        run: |
          echo $'# frozen_string_literal: true\nputs "Hello world!"' > hello.rb
          docker run --rm -v ${PWD}:/app ${{ secrets.DOCKERHUB_USERNAME }}/rubocop:${{ github.ref_name }} -a
